-- ============================================================
-- ClickHouse K-Line Schema Reference
-- ============================================================
--
-- Authoritative DDL generation lives in:
--   internal/cryptooptions/kline.go
--
-- The Go generators create two independent K-line families for the intervals:
--   5m, 15m, 30m, 1h, 4h, 1d
--
-- 1. Option bars
--    Base table: crypto_options_bar_1m
--    Derived objects per interval N:
--      crypto_options_bar_N_agg
--      crypto_options_bar_N_mv
--      crypto_options_bar_N
--
--    Aggregated fields:
--      mark OHLC
--      last OHLC
--      bid OHLC
--      ask OHLC
--      mark_iv open/close
--      bid_iv open
--      ask_iv open
--      greeks (earliest tick)
--      open_interest (latest tick)
--      tick_count (sum)
--
-- 2. Spot bars
--    Base table: crypto_spot_bar_1m
--    Derived objects per interval N:
--      crypto_spot_bar_N_agg
--      crypto_spot_bar_N_mv
--      crypto_spot_bar_N
--
--    Aggregated fields:
--      open/high/low/close
--      price_source
--      tick_count (sum)
--
-- Use the import pipeline or call the Go initializers directly:
--   cryptooptions.InitKlineSchema(...)
--   cryptooptions.InitSpotKlineSchema(...)
--
-- This file is intentionally non-executable to avoid drifting from the
-- generated DDL when the schema evolves.