// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"fmt"
	"net/url"
)


// PriceTargetSummary is a row returned by the FMP PriceTargetSummary endpoint.
type PriceTargetSummary struct {
	Symbol string `json:"symbol"`
	LastMonthCount int64 `json:"lastMonthCount"`
	LastMonthAvgPriceTarget float64 `json:"lastMonthAvgPriceTarget"`
	LastQuarterCount int64 `json:"lastQuarterCount"`
	LastQuarterAvgPriceTarget float64 `json:"lastQuarterAvgPriceTarget"`
	LastYearCount int64 `json:"lastYearCount"`
	LastYearAvgPriceTarget float64 `json:"lastYearAvgPriceTarget"`
	AllTimeCount int64 `json:"allTimeCount"`
	AllTimeAvgPriceTarget float64 `json:"allTimeAvgPriceTarget"`
	Publishers string `json:"publishers"`
}

// PriceTargetConsensus is a row returned by the FMP PriceTargetConsensus endpoint.
type PriceTargetConsensus struct {
	Symbol string `json:"symbol"`
	TargetHigh int64 `json:"targetHigh"`
	TargetLow int64 `json:"targetLow"`
	TargetConsensus float64 `json:"targetConsensus"`
	TargetMedian int64 `json:"targetMedian"`
}

// PriceTargetSummary PriceTargetSummary returns aggregated analyst price target statistics.
func (c *Client) PriceTargetSummary(ctx context.Context, symbol string) (*PriceTargetSummary, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	var out []PriceTargetSummary
	if err := c.get(ctx, "/price-target-summary", params, &out); err != nil {
		return nil, err
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("fmp: no result for PriceTargetSummary")
	}
	return &out[0], nil
}

// PriceTargetConsensus PriceTargetConsensus returns consensus price target (high/low/median/consensus).
func (c *Client) PriceTargetConsensus(ctx context.Context, symbol string) (*PriceTargetConsensus, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	var out []PriceTargetConsensus
	if err := c.get(ctx, "/price-target-consensus", params, &out); err != nil {
		return nil, err
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("fmp: no result for PriceTargetConsensus")
	}
	return &out[0], nil
}
