// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"fmt"
	"net/url"
)


// TreasuryRate is a row returned by the FMP TreasuryRate endpoint.
type TreasuryRate struct {
	Date string `json:"date"`
	Month1 float64 `json:"month1"`
	Month2 float64 `json:"month2"`
	Month3 float64 `json:"month3"`
	Month6 float64 `json:"month6"`
	Year1 float64 `json:"year1"`
	Year2 float64 `json:"year2"`
	Year3 float64 `json:"year3"`
	Year5 float64 `json:"year5"`
	Year7 float64 `json:"year7"`
	Year10 float64 `json:"year10"`
	Year20 float64 `json:"year20"`
	Year30 float64 `json:"year30"`
}

// EconomicIndicator is a row returned by the FMP EconomicIndicator endpoint.
type EconomicIndicator struct {
	Name string `json:"name"`
	Date string `json:"date"`
	Value float64 `json:"value"`
}

// TreasuryRates TreasuryRates returns US Treasury yield curve rates.
func (c *Client) TreasuryRates(ctx context.Context, from string, to string) ([]TreasuryRate, error) {
	params := url.Values{}
	if from != "" {
		params.Set("from", from)
	}
	if to != "" {
		params.Set("to", to)
	}
	var out []TreasuryRate
	if err := c.get(ctx, "/treasury-rates", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// EconomicIndicators EconomicIndicators returns historical values for a macro indicator.
func (c *Client) EconomicIndicators(ctx context.Context, name string, limit int) ([]EconomicIndicator, error) {
	params := url.Values{}
	if name != "" {
		params.Set("name", name)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []EconomicIndicator
	if err := c.get(ctx, "/economic-indicators", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}
