// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"fmt"
	"net/url"
)


// ESGDisclosure is a row returned by the FMP ESGDisclosure endpoint.
type ESGDisclosure struct {
	Date string `json:"date"`
	AcceptedDate string `json:"acceptedDate"`
	Symbol string `json:"symbol"`
	CIK string `json:"cik"`
	CompanyName string `json:"companyName"`
	FormType string `json:"formType"`
	EnvironmentalScore float64 `json:"environmentalScore"`
	SocialScore float64 `json:"socialScore"`
	GovernanceScore float64 `json:"governanceScore"`
	ESGScore float64 `json:"ESGScore"`
	URL string `json:"url"`
}

// ESGRating is a row returned by the FMP ESGRating endpoint.
type ESGRating struct {
	Symbol string `json:"symbol"`
	CIK string `json:"cik"`
	CompanyName string `json:"companyName"`
	Industry string `json:"industry"`
	FiscalYear int64 `json:"fiscalYear"`
	ESGRiskRating string `json:"ESGRiskRating"`
	IndustryRank string `json:"industryRank"`
}

// ESGDisclosures ESGDisclosures returns ESG scores from SEC filings.
func (c *Client) ESGDisclosures(ctx context.Context, symbol string, limit int) ([]ESGDisclosure, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []ESGDisclosure
	if err := c.get(ctx, "/esg-disclosures", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// ESGRatings ESGRatings returns ESG risk rating history for a company.
func (c *Client) ESGRatings(ctx context.Context, symbol string) ([]ESGRating, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	var out []ESGRating
	if err := c.get(ctx, "/esg-ratings", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}
