// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"net/url"
)

// ForexPair describes one forex currency pair from the forex-list.
type ForexPair struct {
	Symbol       string `json:"symbol"`
	FromCurrency string `json:"fromCurrency"`
	ToCurrency   string `json:"toCurrency"`
	FromName     string `json:"fromName"`
	ToName       string `json:"toName"`
}

// ForexList returns all 1,500+ available forex pairs.
func (c *Client) ForexList(ctx context.Context) ([]ForexPair, error) {
	params := url.Values{}
	var out []ForexPair
	if err := c.get(ctx, "/forex-list", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// ForexQuote returns the real-time quote for a forex pair (e.g. "EURUSD", "USDJPY").
// Wraps the shared Quote endpoint.
func (c *Client) ForexQuote(ctx context.Context, symbol string) (*Quote, error) {
	rows, err := c.Quote(ctx, symbol)
	if err != nil {
		return nil, err
	}
	if len(rows) == 0 {
		return nil, nil
	}
	return &rows[0], nil
}

// ForexHistoricalPrices returns daily EOD OHLCV bars for a forex pair.
// Delegates to HistoricalPrices.
func (c *Client) ForexHistoricalPrices(ctx context.Context, symbol, from, to string) ([]EODPrice, error) {
	return c.HistoricalPrices(ctx, symbol, from, to)
}

// ForexIntradayPrices returns intraday bars for a forex pair.
// Delegates to IntradayPrices; valid intervals are Interval1Min … Interval4Hour.
func (c *Client) ForexIntradayPrices(ctx context.Context, symbol string, interval IntradayInterval, from, to string) ([]IntradayBar, error) {
	return c.IntradayPrices(ctx, symbol, interval, from, to)
}
