// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"fmt"
	"net/url"
)

// IncomeStatementGrowth is a row returned by the FMP IncomeStatementGrowth endpoint.
type IncomeStatementGrowth struct {
	Symbol                                    string  `json:"symbol"`
	Date                                      string  `json:"date"`
	FiscalYear                                string  `json:"fiscalYear"`
	Period                                    string  `json:"period"`
	ReportedCurrency                          string  `json:"reportedCurrency"`
	GrowthRevenue                             float64 `json:"growthRevenue"`
	GrowthCostOfRevenue                       float64 `json:"growthCostOfRevenue"`
	GrowthGrossProfit                         float64 `json:"growthGrossProfit"`
	GrowthGrossProfitRatio                    float64 `json:"growthGrossProfitRatio"`
	GrowthResearchAndDevelopmentExpenses      float64 `json:"growthResearchAndDevelopmentExpenses"`
	GrowthGeneralAndAdministrativeExpenses    float64 `json:"growthGeneralAndAdministrativeExpenses"`
	GrowthSellingAndMarketingExpenses         float64 `json:"growthSellingAndMarketingExpenses"`
	GrowthOtherExpenses                       int64   `json:"growthOtherExpenses"`
	GrowthOperatingExpenses                   float64 `json:"growthOperatingExpenses"`
	GrowthCostAndExpenses                     float64 `json:"growthCostAndExpenses"`
	GrowthInterestIncome                      int64   `json:"growthInterestIncome"`
	GrowthInterestExpense                     int64   `json:"growthInterestExpense"`
	GrowthDepreciationAndAmortization         float64 `json:"growthDepreciationAndAmortization"`
	GrowthEBITDA                              float64 `json:"growthEBITDA"`
	GrowthOperatingIncome                     float64 `json:"growthOperatingIncome"`
	GrowthIncomeBeforeTax                     float64 `json:"growthIncomeBeforeTax"`
	GrowthIncomeTaxExpense                    float64 `json:"growthIncomeTaxExpense"`
	GrowthNetIncome                           float64 `json:"growthNetIncome"`
	GrowthEPS                                 float64 `json:"growthEPS"`
	GrowthEPSDiluted                          float64 `json:"growthEPSDiluted"`
	GrowthWeightedAverageShsOut               float64 `json:"growthWeightedAverageShsOut"`
	GrowthWeightedAverageShsOutDil            float64 `json:"growthWeightedAverageShsOutDil"`
	GrowthEBIT                                float64 `json:"growthEBIT"`
	GrowthNonOperatingIncomeExcludingInterest float64 `json:"growthNonOperatingIncomeExcludingInterest"`
	GrowthNetInterestIncome                   int64   `json:"growthNetInterestIncome"`
	GrowthTotalOtherIncomeExpensesNet         float64 `json:"growthTotalOtherIncomeExpensesNet"`
	GrowthNetIncomeFromContinuingOperations   float64 `json:"growthNetIncomeFromContinuingOperations"`
	GrowthOtherAdjustmentsToNetIncome         int64   `json:"growthOtherAdjustmentsToNetIncome"`
	GrowthNetIncomeDeductions                 int64   `json:"growthNetIncomeDeductions"`
}

// BalanceSheetGrowth is a row returned by the FMP BalanceSheetGrowth endpoint.
type BalanceSheetGrowth struct {
	Symbol                                        string  `json:"symbol"`
	Date                                          string  `json:"date"`
	FiscalYear                                    string  `json:"fiscalYear"`
	Period                                        string  `json:"period"`
	ReportedCurrency                              string  `json:"reportedCurrency"`
	GrowthCashAndCashEquivalents                  float64 `json:"growthCashAndCashEquivalents"`
	GrowthShortTermInvestments                    float64 `json:"growthShortTermInvestments"`
	GrowthCashAndShortTermInvestments             float64 `json:"growthCashAndShortTermInvestments"`
	GrowthNetReceivables                          float64 `json:"growthNetReceivables"`
	GrowthInventory                               float64 `json:"growthInventory"`
	GrowthOtherCurrentAssets                      float64 `json:"growthOtherCurrentAssets"`
	GrowthTotalCurrentAssets                      float64 `json:"growthTotalCurrentAssets"`
	GrowthPropertyPlantEquipmentNet               float64 `json:"growthPropertyPlantEquipmentNet"`
	GrowthGoodwill                                int64   `json:"growthGoodwill"`
	GrowthIntangibleAssets                        int64   `json:"growthIntangibleAssets"`
	GrowthGoodwillAndIntangibleAssets             int64   `json:"growthGoodwillAndIntangibleAssets"`
	GrowthLongTermInvestments                     float64 `json:"growthLongTermInvestments"`
	GrowthTaxAssets                               float64 `json:"growthTaxAssets"`
	GrowthOtherNonCurrentAssets                   float64 `json:"growthOtherNonCurrentAssets"`
	GrowthTotalNonCurrentAssets                   float64 `json:"growthTotalNonCurrentAssets"`
	GrowthOtherAssets                             int64   `json:"growthOtherAssets"`
	GrowthTotalAssets                             float64 `json:"growthTotalAssets"`
	GrowthAccountPayables                         float64 `json:"growthAccountPayables"`
	GrowthShortTermDebt                           float64 `json:"growthShortTermDebt"`
	GrowthTaxPayables                             int64   `json:"growthTaxPayables"`
	GrowthDeferredRevenue                         float64 `json:"growthDeferredRevenue"`
	GrowthOtherCurrentLiabilities                 float64 `json:"growthOtherCurrentLiabilities"`
	GrowthTotalCurrentLiabilities                 float64 `json:"growthTotalCurrentLiabilities"`
	GrowthLongTermDebt                            float64 `json:"growthLongTermDebt"`
	GrowthDeferredRevenueNonCurrent               int64   `json:"growthDeferredRevenueNonCurrent"`
	GrowthDeferredTaxLiabilitiesNonCurrent        int64   `json:"growthDeferredTaxLiabilitiesNonCurrent"`
	GrowthOtherNonCurrentLiabilities              float64 `json:"growthOtherNonCurrentLiabilities"`
	GrowthTotalNonCurrentLiabilities              float64 `json:"growthTotalNonCurrentLiabilities"`
	GrowthOtherLiabilities                        int64   `json:"growthOtherLiabilities"`
	GrowthTotalLiabilities                        float64 `json:"growthTotalLiabilities"`
	GrowthPreferredStock                          int64   `json:"growthPreferredStock"`
	GrowthCommonStock                             float64 `json:"growthCommonStock"`
	GrowthRetainedEarnings                        float64 `json:"growthRetainedEarnings"`
	GrowthAccumulatedOtherComprehensiveIncomeLoss float64 `json:"growthAccumulatedOtherComprehensiveIncomeLoss"`
	GrowthOthertotalStockholdersEquity            int64   `json:"growthOthertotalStockholdersEquity"`
	GrowthTotalStockholdersEquity                 float64 `json:"growthTotalStockholdersEquity"`
	GrowthMinorityInterest                        int64   `json:"growthMinorityInterest"`
	GrowthTotalEquity                             float64 `json:"growthTotalEquity"`
	GrowthTotalLiabilitiesAndStockholdersEquity   float64 `json:"growthTotalLiabilitiesAndStockholdersEquity"`
	GrowthTotalInvestments                        float64 `json:"growthTotalInvestments"`
	GrowthTotalDebt                               float64 `json:"growthTotalDebt"`
	GrowthNetDebt                                 float64 `json:"growthNetDebt"`
	GrowthAccountsReceivables                     float64 `json:"growthAccountsReceivables"`
	GrowthOtherReceivables                        float64 `json:"growthOtherReceivables"`
	GrowthPrepaids                                int64   `json:"growthPrepaids"`
	GrowthTotalPayables                           float64 `json:"growthTotalPayables"`
	GrowthOtherPayables                           float64 `json:"growthOtherPayables"`
	GrowthAccruedExpenses                         int64   `json:"growthAccruedExpenses"`
	GrowthCapitalLeaseObligationsCurrent          float64 `json:"growthCapitalLeaseObligationsCurrent"`
	GrowthAdditionalPaidInCapital                 int64   `json:"growthAdditionalPaidInCapital"`
	GrowthTreasuryStock                           int64   `json:"growthTreasuryStock"`
}

// CashFlowGrowth is a row returned by the FMP CashFlowGrowth endpoint.
type CashFlowGrowth struct {
	Symbol                                         string  `json:"symbol"`
	Date                                           string  `json:"date"`
	FiscalYear                                     string  `json:"fiscalYear"`
	Period                                         string  `json:"period"`
	ReportedCurrency                               string  `json:"reportedCurrency"`
	GrowthNetIncome                                float64 `json:"growthNetIncome"`
	GrowthDepreciationAndAmortization              float64 `json:"growthDepreciationAndAmortization"`
	GrowthDeferredIncomeTax                        int64   `json:"growthDeferredIncomeTax"`
	GrowthStockBasedCompensation                   float64 `json:"growthStockBasedCompensation"`
	GrowthChangeInWorkingCapital                   float64 `json:"growthChangeInWorkingCapital"`
	GrowthAccountsReceivables                      float64 `json:"growthAccountsReceivables"`
	GrowthInventory                                float64 `json:"growthInventory"`
	GrowthAccountsPayables                         float64 `json:"growthAccountsPayables"`
	GrowthOtherWorkingCapital                      float64 `json:"growthOtherWorkingCapital"`
	GrowthOtherNonCashItems                        float64 `json:"growthOtherNonCashItems"`
	GrowthNetCashProvidedByOperatingActivites      float64 `json:"growthNetCashProvidedByOperatingActivites"`
	GrowthInvestmentsInPropertyPlantAndEquipment   float64 `json:"growthInvestmentsInPropertyPlantAndEquipment"`
	GrowthAcquisitionsNet                          int64   `json:"growthAcquisitionsNet"`
	GrowthPurchasesOfInvestments                   float64 `json:"growthPurchasesOfInvestments"`
	GrowthSalesMaturitiesOfInvestments             float64 `json:"growthSalesMaturitiesOfInvestments"`
	GrowthOtherInvestingActivites                  float64 `json:"growthOtherInvestingActivites"`
	GrowthNetCashUsedForInvestingActivites         float64 `json:"growthNetCashUsedForInvestingActivites"`
	GrowthDebtRepayment                            float64 `json:"growthDebtRepayment"`
	GrowthCommonStockIssued                        int64   `json:"growthCommonStockIssued"`
	GrowthCommonStockRepurchased                   float64 `json:"growthCommonStockRepurchased"`
	GrowthDividendsPaid                            float64 `json:"growthDividendsPaid"`
	GrowthOtherFinancingActivites                  float64 `json:"growthOtherFinancingActivites"`
	GrowthNetCashUsedProvidedByFinancingActivities float64 `json:"growthNetCashUsedProvidedByFinancingActivities"`
	GrowthEffectOfForexChangesOnCash               int64   `json:"growthEffectOfForexChangesOnCash"`
	GrowthNetChangeInCash                          float64 `json:"growthNetChangeInCash"`
	GrowthCashAtEndOfPeriod                        float64 `json:"growthCashAtEndOfPeriod"`
	GrowthCashAtBeginningOfPeriod                  float64 `json:"growthCashAtBeginningOfPeriod"`
	GrowthOperatingCashFlow                        float64 `json:"growthOperatingCashFlow"`
	GrowthCapitalExpenditure                       float64 `json:"growthCapitalExpenditure"`
	GrowthFreeCashFlow                             float64 `json:"growthFreeCashFlow"`
	GrowthNetDebtIssuance                          float64 `json:"growthNetDebtIssuance"`
	GrowthLongTermNetDebtIssuance                  float64 `json:"growthLongTermNetDebtIssuance"`
	GrowthShortTermNetDebtIssuance                 float64 `json:"growthShortTermNetDebtIssuance"`
	GrowthNetStockIssuance                         float64 `json:"growthNetStockIssuance"`
	GrowthPreferredDividendsPaid                   float64 `json:"growthPreferredDividendsPaid"`
	GrowthIncomeTaxesPaid                          float64 `json:"growthIncomeTaxesPaid"`
	GrowthInterestPaid                             int64   `json:"growthInterestPaid"`
}

// IncomeGrowth IncomeStatementGrowth returns YoY growth rates for income statement items.
func (c *Client) IncomeGrowth(ctx context.Context, symbol string, period string, limit int) ([]IncomeStatementGrowth, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if period != "" {
		params.Set("period", period)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []IncomeStatementGrowth
	if err := c.get(ctx, "/income-statement-growth", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceSheetGrowth BalanceSheetGrowth returns YoY growth rates for balance sheet items.
func (c *Client) BalanceSheetGrowth(ctx context.Context, symbol string, period string, limit int) ([]BalanceSheetGrowth, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if period != "" {
		params.Set("period", period)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []BalanceSheetGrowth
	if err := c.get(ctx, "/balance-sheet-statement-growth", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// CashFlowGrowth CashFlowGrowth returns YoY growth rates for cash flow items.
func (c *Client) CashFlowGrowth(ctx context.Context, symbol string, period string, limit int) ([]CashFlowGrowth, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if period != "" {
		params.Set("period", period)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []CashFlowGrowth
	if err := c.get(ctx, "/cash-flow-statement-growth", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}
