// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"fmt"
	"net/url"
)


// IndexInfo is one row in the full list of tradable indexes.
type IndexInfo struct {
	Symbol string `json:"symbol"`
	Name string `json:"name"`
	Exchange string `json:"exchange"`
	Currency string `json:"currency"`
}

// IndexConstituent is a current member of a major index (S&P 500 / Nasdaq-100 / Dow Jones).
type IndexConstituent struct {
	Symbol string `json:"symbol"`
	Name string `json:"name"`
	Sector string `json:"sector"`
	SubSector string `json:"subSector"`
	HeadQuarter string `json:"headQuarter"`
	DateFirstAdded string `json:"dateFirstAdded"`
	CIK string `json:"cik"`
	Founded string `json:"founded"`
}

// IndexConstituentChange records an addition or removal from an index.
type IndexConstituentChange struct {
	DateAdded string `json:"dateAdded"`
	AddedSecurity string `json:"addedSecurity"`
	RemovedTicker string `json:"removedTicker"`
	RemovedSecurity string `json:"removedSecurity"`
	Date string `json:"date"`
	Symbol string `json:"symbol"`
	Reason string `json:"reason"`
}

// MarketRiskPremium holds equity risk premium data by country.
type MarketRiskPremium struct {
	Country string `json:"country"`
	Continent string `json:"continent"`
	CountryRiskPremium float64 `json:"countryRiskPremium"`
	TotalEquityRiskPremium float64 `json:"totalEquityRiskPremium"`
}

// IndexList returns all tradable index symbols (424+).
func (c *Client) IndexList(ctx context.Context) ([]IndexInfo, error) {
	params := url.Values{}
	var out []IndexInfo
	if err := c.get(ctx, "/index-list", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// SP500Constituents returns current S&P 500 members.
func (c *Client) SP500Constituents(ctx context.Context) ([]IndexConstituent, error) {
	params := url.Values{}
	var out []IndexConstituent
	if err := c.get(ctx, "/sp500-constituent", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// NasdaqConstituents returns current Nasdaq-100 members.
func (c *Client) NasdaqConstituents(ctx context.Context) ([]IndexConstituent, error) {
	params := url.Values{}
	var out []IndexConstituent
	if err := c.get(ctx, "/nasdaq-constituent", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// DowJonesConstituents returns current Dow Jones members.
func (c *Client) DowJonesConstituents(ctx context.Context) ([]IndexConstituent, error) {
	params := url.Values{}
	var out []IndexConstituent
	if err := c.get(ctx, "/dowjones-constituent", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// HistoricalSP500Changes returns S&P 500 addition/removal history.
func (c *Client) HistoricalSP500Changes(ctx context.Context, limit int) ([]IndexConstituentChange, error) {
	params := url.Values{}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []IndexConstituentChange
	if err := c.get(ctx, "/historical-sp500-constituent", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// HistoricalNasdaqChanges returns Nasdaq-100 addition/removal history.
func (c *Client) HistoricalNasdaqChanges(ctx context.Context, limit int) ([]IndexConstituentChange, error) {
	params := url.Values{}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []IndexConstituentChange
	if err := c.get(ctx, "/historical-nasdaq-constituent", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// HistoricalDowJonesChanges returns Dow Jones addition/removal history.
func (c *Client) HistoricalDowJonesChanges(ctx context.Context, limit int) ([]IndexConstituentChange, error) {
	params := url.Values{}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []IndexConstituentChange
	if err := c.get(ctx, "/historical-dowjones-constituent", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// MarketRiskPremium returns equity risk premium by country.
func (c *Client) MarketRiskPremium(ctx context.Context) ([]MarketRiskPremium, error) {
	params := url.Values{}
	var out []MarketRiskPremium
	if err := c.get(ctx, "/market-risk-premium", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// IndexPrices fetches OHLCV history for any index symbol (e.g. "^GSPC", "^IXIC", "^DJI", "^VIX").
// Use c.HistoricalPrices(ctx, "^GSPC", from, to) — same EODPrice struct, same endpoint.
