// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"fmt"
	"net/url"
)

// SP500Change is a row returned by the FMP SP500Change endpoint.
type SP500Change struct {
	DateAdded       string `json:"dateAdded"`
	AddedSecurity   string `json:"addedSecurity"`
	RemovedTicker   string `json:"removedTicker"`
	RemovedSecurity string `json:"removedSecurity"`
	Date            string `json:"date"`
	Symbol          string `json:"symbol"`
	Reason          string `json:"reason"`
}

// SectorPE is a row returned by the FMP SectorPE endpoint.
type SectorPE struct {
	Date     string  `json:"date"`
	Sector   string  `json:"sector"`
	Exchange string  `json:"exchange"`
	PE       float64 `json:"pe"`
}

// HistoricalSP500 HistoricalSP500Constituents returns S&P 500 addition/removal history.
func (c *Client) HistoricalSP500(ctx context.Context, limit int) ([]SP500Change, error) {
	params := url.Values{}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []SP500Change
	if err := c.get(ctx, "/historical-sp500-constituent", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// HistoricalSectorPE HistoricalSectorPE returns historical P/E ratios by sector.
func (c *Client) HistoricalSectorPE(ctx context.Context, sector string, exchange string, from string, to string, limit int) ([]SectorPE, error) {
	params := url.Values{}
	if sector != "" {
		params.Set("sector", sector)
	}
	if exchange != "" {
		params.Set("exchange", exchange)
	}
	if from != "" {
		params.Set("from", from)
	}
	if to != "" {
		params.Set("to", to)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []SectorPE
	if err := c.get(ctx, "/historical-sector-pe", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}
