// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"fmt"
	"net/url"
)

// NewsArticle is a row returned by the FMP NewsArticle endpoint.
type NewsArticle struct {
	Symbol        string `json:"symbol"`
	PublishedDate string `json:"publishedDate"`
	Publisher     string `json:"publisher"`
	Title         string `json:"title"`
	Image         string `json:"image"`
	Site          string `json:"site"`
	Text          string `json:"text"`
	URL           string `json:"url"`
}

// ForexNewsArticle is a row returned by the FMP ForexNewsArticle endpoint.
type ForexNewsArticle struct {
	Symbol        string `json:"symbol"`
	PublishedDate string `json:"publishedDate"`
	Publisher     string `json:"publisher"`
	Title         string `json:"title"`
	Image         string `json:"image"`
	Site          string `json:"site"`
	Text          string `json:"text"`
	URL           string `json:"url"`
}

// CryptoNewsArticle is a row returned by the FMP CryptoNewsArticle endpoint.
type CryptoNewsArticle struct {
	Symbol        string  `json:"symbol"`
	PublishedDate string  `json:"publishedDate"`
	Publisher     string  `json:"publisher"`
	Title         string  `json:"title"`
	Image         *string `json:"image"`
	Site          string  `json:"site"`
	Text          string  `json:"text"`
	URL           string  `json:"url"`
}

// PressRelease is a row returned by the FMP PressRelease endpoint.
type PressRelease struct {
	Symbol        string `json:"symbol"`
	PublishedDate string `json:"publishedDate"`
	Publisher     string `json:"publisher"`
	Title         string `json:"title"`
	Image         string `json:"image"`
	Site          string `json:"site"`
	Text          string `json:"text"`
	URL           string `json:"url"`
}

// StockNews StockNews returns recent news articles for a symbol.
func (c *Client) StockNews(ctx context.Context, symbol string, limit int) ([]NewsArticle, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []NewsArticle
	if err := c.get(ctx, "/news/stock", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// ForexNews ForexNews returns recent forex market news.
func (c *Client) ForexNews(ctx context.Context, symbol string, limit int) ([]ForexNewsArticle, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []ForexNewsArticle
	if err := c.get(ctx, "/news/forex", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoNews CryptoNews returns recent crypto market news.
func (c *Client) CryptoNews(ctx context.Context, limit int) ([]CryptoNewsArticle, error) {
	params := url.Values{}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []CryptoNewsArticle
	if err := c.get(ctx, "/news/crypto", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// PressReleases PressReleases returns press releases for a symbol.
func (c *Client) PressReleases(ctx context.Context, symbol string, limit int) ([]PressRelease, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []PressRelease
	if err := c.get(ctx, "/news/press-releases", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}
