// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"net/url"
)


// EODPrice is a row returned by the FMP EODPrice endpoint.
type EODPrice struct {
	Symbol string `json:"symbol"`
	Date string `json:"date"`
	Open float64 `json:"open"`
	High float64 `json:"high"`
	Low float64 `json:"low"`
	Close float64 `json:"close"`
	Volume int64 `json:"volume"`
	Change float64 `json:"change"`
	ChangePercent float64 `json:"changePercent"`
	Vwap float64 `json:"vwap"`
}

// AdjustedPrice is a row returned by the FMP AdjustedPrice endpoint.
type AdjustedPrice struct {
	Symbol string `json:"symbol"`
	Date string `json:"date"`
	AdjOpen float64 `json:"adjOpen"`
	AdjHigh float64 `json:"adjHigh"`
	AdjLow float64 `json:"adjLow"`
	AdjClose float64 `json:"adjClose"`
	Volume int64 `json:"volume"`
}

// HistoricalPrices HistoricalPrices returns daily EOD OHLCV price bars.
func (c *Client) HistoricalPrices(ctx context.Context, symbol string, from string, to string) ([]EODPrice, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if from != "" {
		params.Set("from", from)
	}
	if to != "" {
		params.Set("to", to)
	}
	var out []EODPrice
	if err := c.get(ctx, "/historical-price-eod/full", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// AdjustedPrices AdjustedPrices returns dividend-adjusted historical prices.
func (c *Client) AdjustedPrices(ctx context.Context, symbol string, from string, to string) ([]AdjustedPrice, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if from != "" {
		params.Set("from", from)
	}
	if to != "" {
		params.Set("to", to)
	}
	var out []AdjustedPrice
	if err := c.get(ctx, "/historical-price-eod/dividend-adjusted", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}
