// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"fmt"
	"net/url"
)

// Ratios is a row returned by the FMP Ratios endpoint.
type Ratios struct {
	Symbol                                  string  `json:"symbol"`
	Date                                    string  `json:"date"`
	FiscalYear                              string  `json:"fiscalYear"`
	Period                                  string  `json:"period"`
	ReportedCurrency                        string  `json:"reportedCurrency"`
	GrossProfitMargin                       float64 `json:"grossProfitMargin"`
	EBITMargin                              float64 `json:"ebitMargin"`
	EBITDAMargin                            float64 `json:"ebitdaMargin"`
	OperatingProfitMargin                   float64 `json:"operatingProfitMargin"`
	PretaxProfitMargin                      float64 `json:"pretaxProfitMargin"`
	ContinuousOperationsProfitMargin        float64 `json:"continuousOperationsProfitMargin"`
	NetProfitMargin                         float64 `json:"netProfitMargin"`
	BottomLineProfitMargin                  float64 `json:"bottomLineProfitMargin"`
	ReceivablesTurnover                     float64 `json:"receivablesTurnover"`
	PayablesTurnover                        float64 `json:"payablesTurnover"`
	InventoryTurnover                       float64 `json:"inventoryTurnover"`
	FixedAssetTurnover                      float64 `json:"fixedAssetTurnover"`
	AssetTurnover                           float64 `json:"assetTurnover"`
	CurrentRatio                            float64 `json:"currentRatio"`
	QuickRatio                              float64 `json:"quickRatio"`
	SolvencyRatio                           float64 `json:"solvencyRatio"`
	CashRatio                               float64 `json:"cashRatio"`
	PriceToEarningsRatio                    float64 `json:"priceToEarningsRatio"`
	PriceToEarningsGrowthRatio              float64 `json:"priceToEarningsGrowthRatio"`
	ForwardPriceToEarningsGrowthRatio       float64 `json:"forwardPriceToEarningsGrowthRatio"`
	PriceToBookRatio                        float64 `json:"priceToBookRatio"`
	PriceToSalesRatio                       float64 `json:"priceToSalesRatio"`
	PriceToFreeCashFlowRatio                float64 `json:"priceToFreeCashFlowRatio"`
	PriceToOperatingCashFlowRatio           float64 `json:"priceToOperatingCashFlowRatio"`
	DebtToAssetsRatio                       float64 `json:"debtToAssetsRatio"`
	DebtToEquityRatio                       float64 `json:"debtToEquityRatio"`
	DebtToCapitalRatio                      float64 `json:"debtToCapitalRatio"`
	LongTermDebtToCapitalRatio              float64 `json:"longTermDebtToCapitalRatio"`
	FinancialLeverageRatio                  float64 `json:"financialLeverageRatio"`
	WorkingCapitalTurnoverRatio             float64 `json:"workingCapitalTurnoverRatio"`
	OperatingCashFlowRatio                  float64 `json:"operatingCashFlowRatio"`
	OperatingCashFlowSalesRatio             float64 `json:"operatingCashFlowSalesRatio"`
	FreeCashFlowOperatingCashFlowRatio      float64 `json:"freeCashFlowOperatingCashFlowRatio"`
	DebtServiceCoverageRatio                float64 `json:"debtServiceCoverageRatio"`
	InterestCoverageRatio                   float64 `json:"interestCoverageRatio"`
	ShortTermOperatingCashFlowCoverageRatio float64 `json:"shortTermOperatingCashFlowCoverageRatio"`
	OperatingCashFlowCoverageRatio          float64 `json:"operatingCashFlowCoverageRatio"`
	CapitalExpenditureCoverageRatio         float64 `json:"capitalExpenditureCoverageRatio"`
	DividendPaidAndCapexCoverageRatio       float64 `json:"dividendPaidAndCapexCoverageRatio"`
	DividendPayoutRatio                     float64 `json:"dividendPayoutRatio"`
	DividendYield                           float64 `json:"dividendYield"`
	DividendYieldPercentage                 float64 `json:"dividendYieldPercentage"`
	RevenuePerShare                         float64 `json:"revenuePerShare"`
	NetIncomePerShare                       float64 `json:"netIncomePerShare"`
	InterestDebtPerShare                    float64 `json:"interestDebtPerShare"`
	CashPerShare                            float64 `json:"cashPerShare"`
	BookValuePerShare                       float64 `json:"bookValuePerShare"`
	TangibleBookValuePerShare               float64 `json:"tangibleBookValuePerShare"`
	ShareholdersEquityPerShare              float64 `json:"shareholdersEquityPerShare"`
	OperatingCashFlowPerShare               float64 `json:"operatingCashFlowPerShare"`
	CapexPerShare                           float64 `json:"capexPerShare"`
	FreeCashFlowPerShare                    float64 `json:"freeCashFlowPerShare"`
	NetIncomePerEbt                         float64 `json:"netIncomePerEBT"`
	EbtPerEBIT                              float64 `json:"ebtPerEbit"`
	PriceToFairValue                        float64 `json:"priceToFairValue"`
	DebtToMarketCap                         float64 `json:"debtToMarketCap"`
	EffectiveTaxRate                        float64 `json:"effectiveTaxRate"`
	EnterpriseValueMultiple                 float64 `json:"enterpriseValueMultiple"`
	DividendPerShare                        float64 `json:"dividendPerShare"`
}

// RatiosTTM is a row returned by the FMP RatiosTTM endpoint.
type RatiosTTM struct {
	Symbol                                     string  `json:"symbol"`
	GrossProfitMarginTtm                       float64 `json:"grossProfitMarginTTM"`
	EBITMarginTtm                              float64 `json:"ebitMarginTTM"`
	EBITDAMarginTtm                            float64 `json:"ebitdaMarginTTM"`
	OperatingProfitMarginTtm                   float64 `json:"operatingProfitMarginTTM"`
	PretaxProfitMarginTtm                      float64 `json:"pretaxProfitMarginTTM"`
	ContinuousOperationsProfitMarginTtm        float64 `json:"continuousOperationsProfitMarginTTM"`
	NetProfitMarginTtm                         float64 `json:"netProfitMarginTTM"`
	BottomLineProfitMarginTtm                  float64 `json:"bottomLineProfitMarginTTM"`
	ReceivablesTurnoverTtm                     float64 `json:"receivablesTurnoverTTM"`
	PayablesTurnoverTtm                        float64 `json:"payablesTurnoverTTM"`
	InventoryTurnoverTtm                       float64 `json:"inventoryTurnoverTTM"`
	FixedAssetTurnoverTtm                      float64 `json:"fixedAssetTurnoverTTM"`
	AssetTurnoverTtm                           float64 `json:"assetTurnoverTTM"`
	CurrentRatioTtm                            float64 `json:"currentRatioTTM"`
	QuickRatioTtm                              float64 `json:"quickRatioTTM"`
	SolvencyRatioTtm                           float64 `json:"solvencyRatioTTM"`
	CashRatioTtm                               float64 `json:"cashRatioTTM"`
	PriceToEarningsRatioTtm                    float64 `json:"priceToEarningsRatioTTM"`
	PriceToEarningsGrowthRatioTtm              float64 `json:"priceToEarningsGrowthRatioTTM"`
	ForwardPriceToEarningsGrowthRatioTtm       float64 `json:"forwardPriceToEarningsGrowthRatioTTM"`
	PriceToBookRatioTtm                        float64 `json:"priceToBookRatioTTM"`
	PriceToSalesRatioTtm                       float64 `json:"priceToSalesRatioTTM"`
	PriceToFreeCashFlowRatioTtm                float64 `json:"priceToFreeCashFlowRatioTTM"`
	PriceToOperatingCashFlowRatioTtm           float64 `json:"priceToOperatingCashFlowRatioTTM"`
	DebtToAssetsRatioTtm                       float64 `json:"debtToAssetsRatioTTM"`
	DebtToEquityRatioTtm                       float64 `json:"debtToEquityRatioTTM"`
	DebtToCapitalRatioTtm                      float64 `json:"debtToCapitalRatioTTM"`
	LongTermDebtToCapitalRatioTtm              float64 `json:"longTermDebtToCapitalRatioTTM"`
	FinancialLeverageRatioTtm                  float64 `json:"financialLeverageRatioTTM"`
	WorkingCapitalTurnoverRatioTtm             float64 `json:"workingCapitalTurnoverRatioTTM"`
	OperatingCashFlowRatioTtm                  float64 `json:"operatingCashFlowRatioTTM"`
	OperatingCashFlowSalesRatioTtm             float64 `json:"operatingCashFlowSalesRatioTTM"`
	FreeCashFlowOperatingCashFlowRatioTtm      float64 `json:"freeCashFlowOperatingCashFlowRatioTTM"`
	DebtServiceCoverageRatioTtm                float64 `json:"debtServiceCoverageRatioTTM"`
	InterestCoverageRatioTtm                   float64 `json:"interestCoverageRatioTTM"`
	ShortTermOperatingCashFlowCoverageRatioTtm float64 `json:"shortTermOperatingCashFlowCoverageRatioTTM"`
	OperatingCashFlowCoverageRatioTtm          float64 `json:"operatingCashFlowCoverageRatioTTM"`
	CapitalExpenditureCoverageRatioTtm         float64 `json:"capitalExpenditureCoverageRatioTTM"`
	DividendPaidAndCapexCoverageRatioTtm       float64 `json:"dividendPaidAndCapexCoverageRatioTTM"`
	DividendPayoutRatioTtm                     float64 `json:"dividendPayoutRatioTTM"`
	DividendYieldTtm                           float64 `json:"dividendYieldTTM"`
	EnterpriseValueTtm                         int64   `json:"enterpriseValueTTM"`
	RevenuePerShareTtm                         float64 `json:"revenuePerShareTTM"`
	NetIncomePerShareTtm                       float64 `json:"netIncomePerShareTTM"`
	InterestDebtPerShareTtm                    float64 `json:"interestDebtPerShareTTM"`
	CashPerShareTtm                            float64 `json:"cashPerShareTTM"`
	BookValuePerShareTtm                       float64 `json:"bookValuePerShareTTM"`
	TangibleBookValuePerShareTtm               float64 `json:"tangibleBookValuePerShareTTM"`
	ShareholdersEquityPerShareTtm              float64 `json:"shareholdersEquityPerShareTTM"`
	OperatingCashFlowPerShareTtm               float64 `json:"operatingCashFlowPerShareTTM"`
	CapexPerShareTtm                           float64 `json:"capexPerShareTTM"`
	FreeCashFlowPerShareTtm                    float64 `json:"freeCashFlowPerShareTTM"`
	NetIncomePerEbtttm                         float64 `json:"netIncomePerEBTTTM"`
	EbtPerEBITTtm                              float64 `json:"ebtPerEbitTTM"`
	PriceToFairValueTtm                        float64 `json:"priceToFairValueTTM"`
	DebtToMarketCapTtm                         float64 `json:"debtToMarketCapTTM"`
	EffectiveTaxRateTtm                        float64 `json:"effectiveTaxRateTTM"`
	EnterpriseValueMultipleTtm                 float64 `json:"enterpriseValueMultipleTTM"`
	DividendPerShareTtm                        float64 `json:"dividendPerShareTTM"`
}

// KeyMetrics is a row returned by the FMP KeyMetrics endpoint.
type KeyMetrics struct {
	Symbol                                 string  `json:"symbol"`
	Date                                   string  `json:"date"`
	FiscalYear                             string  `json:"fiscalYear"`
	Period                                 string  `json:"period"`
	ReportedCurrency                       string  `json:"reportedCurrency"`
	MarketCap                              int64   `json:"marketCap"`
	EnterpriseValue                        int64   `json:"enterpriseValue"`
	EvToSales                              float64 `json:"evToSales"`
	EvToOperatingCashFlow                  float64 `json:"evToOperatingCashFlow"`
	EvToFreeCashFlow                       float64 `json:"evToFreeCashFlow"`
	EvToEBITDA                             float64 `json:"evToEBITDA"`
	NetDebtToEBITDA                        float64 `json:"netDebtToEBITDA"`
	CurrentRatio                           float64 `json:"currentRatio"`
	IncomeQuality                          float64 `json:"incomeQuality"`
	GrahamNumber                           float64 `json:"grahamNumber"`
	GrahamNetNet                           float64 `json:"grahamNetNet"`
	TaxBurden                              float64 `json:"taxBurden"`
	InterestBurden                         int64   `json:"interestBurden"`
	WorkingCapital                         int64   `json:"workingCapital"`
	InvestedCapital                        int64   `json:"investedCapital"`
	ReturnOnAssets                         float64 `json:"returnOnAssets"`
	OperatingReturnOnAssets                float64 `json:"operatingReturnOnAssets"`
	ReturnOnTangibleAssets                 float64 `json:"returnOnTangibleAssets"`
	ReturnOnEquity                         float64 `json:"returnOnEquity"`
	ReturnOnInvestedCapital                float64 `json:"returnOnInvestedCapital"`
	ReturnOnCapitalEmployed                float64 `json:"returnOnCapitalEmployed"`
	EarningsYield                          float64 `json:"earningsYield"`
	FreeCashFlowYield                      float64 `json:"freeCashFlowYield"`
	CapexToOperatingCashFlow               float64 `json:"capexToOperatingCashFlow"`
	CapexToDepreciation                    float64 `json:"capexToDepreciation"`
	CapexToRevenue                         float64 `json:"capexToRevenue"`
	SalesGeneralAndAdministrativeToRevenue float64 `json:"salesGeneralAndAdministrativeToRevenue"`
	ResearchAndDevelopementToRevenue       float64 `json:"researchAndDevelopementToRevenue"`
	StockBasedCompensationToRevenue        float64 `json:"stockBasedCompensationToRevenue"`
	IntangiblesToTotalAssets               int64   `json:"intangiblesToTotalAssets"`
	AverageReceivables                     int64   `json:"averageReceivables"`
	AveragePayables                        int64   `json:"averagePayables"`
	AverageInventory                       int64   `json:"averageInventory"`
	DaysOfSalesOutstanding                 float64 `json:"daysOfSalesOutstanding"`
	DaysOfPayablesOutstanding              float64 `json:"daysOfPayablesOutstanding"`
	DaysOfInventoryOutstanding             float64 `json:"daysOfInventoryOutstanding"`
	OperatingCycle                         float64 `json:"operatingCycle"`
	CashConversionCycle                    float64 `json:"cashConversionCycle"`
	FreeCashFlowToEquity                   int64   `json:"freeCashFlowToEquity"`
	FreeCashFlowToFirm                     int64   `json:"freeCashFlowToFirm"`
	TangibleAssetValue                     int64   `json:"tangibleAssetValue"`
	NetCurrentAssetValue                   int64   `json:"netCurrentAssetValue"`
}

// KeyMetricsTTM is a row returned by the FMP KeyMetricsTTM endpoint.
type KeyMetricsTTM struct {
	Symbol                                    string  `json:"symbol"`
	MarketCap                                 int64   `json:"marketCap"`
	EnterpriseValueTtm                        int64   `json:"enterpriseValueTTM"`
	EvToSalesTtm                              float64 `json:"evToSalesTTM"`
	EvToOperatingCashFlowTtm                  float64 `json:"evToOperatingCashFlowTTM"`
	EvToFreeCashFlowTtm                       float64 `json:"evToFreeCashFlowTTM"`
	EvToEbitdattm                             float64 `json:"evToEBITDATTM"`
	NetDebtToEbitdattm                        float64 `json:"netDebtToEBITDATTM"`
	CurrentRatioTtm                           float64 `json:"currentRatioTTM"`
	IncomeQualityTtm                          float64 `json:"incomeQualityTTM"`
	GrahamNumberTtm                           float64 `json:"grahamNumberTTM"`
	GrahamNetNetTtm                           float64 `json:"grahamNetNetTTM"`
	TaxBurdenTtm                              float64 `json:"taxBurdenTTM"`
	InterestBurdenTtm                         int64   `json:"interestBurdenTTM"`
	WorkingCapitalTtm                         int64   `json:"workingCapitalTTM"`
	InvestedCapitalTtm                        int64   `json:"investedCapitalTTM"`
	ReturnOnAssetsTtm                         float64 `json:"returnOnAssetsTTM"`
	OperatingReturnOnAssetsTtm                float64 `json:"operatingReturnOnAssetsTTM"`
	ReturnOnTangibleAssetsTtm                 float64 `json:"returnOnTangibleAssetsTTM"`
	ReturnOnEquityTtm                         float64 `json:"returnOnEquityTTM"`
	ReturnOnInvestedCapitalTtm                float64 `json:"returnOnInvestedCapitalTTM"`
	ReturnOnCapitalEmployedTtm                float64 `json:"returnOnCapitalEmployedTTM"`
	EarningsYieldTtm                          float64 `json:"earningsYieldTTM"`
	FreeCashFlowYieldTtm                      float64 `json:"freeCashFlowYieldTTM"`
	CapexToOperatingCashFlowTtm               float64 `json:"capexToOperatingCashFlowTTM"`
	CapexToDepreciationTtm                    float64 `json:"capexToDepreciationTTM"`
	CapexToRevenueTtm                         float64 `json:"capexToRevenueTTM"`
	SalesGeneralAndAdministrativeToRevenueTtm float64 `json:"salesGeneralAndAdministrativeToRevenueTTM"`
	ResearchAndDevelopementToRevenueTtm       float64 `json:"researchAndDevelopementToRevenueTTM"`
	StockBasedCompensationToRevenueTtm        float64 `json:"stockBasedCompensationToRevenueTTM"`
	IntangiblesToTotalAssetsTtm               int64   `json:"intangiblesToTotalAssetsTTM"`
	AverageReceivablesTtm                     int64   `json:"averageReceivablesTTM"`
	AveragePayablesTtm                        int64   `json:"averagePayablesTTM"`
	AverageInventoryTtm                       int64   `json:"averageInventoryTTM"`
	DaysOfSalesOutstandingTtm                 float64 `json:"daysOfSalesOutstandingTTM"`
	DaysOfPayablesOutstandingTtm              float64 `json:"daysOfPayablesOutstandingTTM"`
	DaysOfInventoryOutstandingTtm             float64 `json:"daysOfInventoryOutstandingTTM"`
	OperatingCycleTtm                         float64 `json:"operatingCycleTTM"`
	CashConversionCycleTtm                    float64 `json:"cashConversionCycleTTM"`
	FreeCashFlowToEquityTtm                   int64   `json:"freeCashFlowToEquityTTM"`
	FreeCashFlowToFirmTtm                     int64   `json:"freeCashFlowToFirmTTM"`
	TangibleAssetValueTtm                     int64   `json:"tangibleAssetValueTTM"`
	NetCurrentAssetValueTtm                   int64   `json:"netCurrentAssetValueTTM"`
}

// FinancialGrowth is a row returned by the FMP FinancialGrowth endpoint.
type FinancialGrowth struct {
	Symbol                                  string  `json:"symbol"`
	Date                                    string  `json:"date"`
	FiscalYear                              string  `json:"fiscalYear"`
	Period                                  string  `json:"period"`
	ReportedCurrency                        string  `json:"reportedCurrency"`
	RevenueGrowth                           float64 `json:"revenueGrowth"`
	GrossProfitGrowth                       float64 `json:"grossProfitGrowth"`
	Ebitgrowth                              float64 `json:"ebitgrowth"`
	OperatingIncomeGrowth                   float64 `json:"operatingIncomeGrowth"`
	NetIncomeGrowth                         float64 `json:"netIncomeGrowth"`
	Epsgrowth                               float64 `json:"epsgrowth"`
	EpsdilutedGrowth                        float64 `json:"epsdilutedGrowth"`
	WeightedAverageSharesGrowth             float64 `json:"weightedAverageSharesGrowth"`
	WeightedAverageSharesDilutedGrowth      float64 `json:"weightedAverageSharesDilutedGrowth"`
	DividendsPerShareGrowth                 float64 `json:"dividendsPerShareGrowth"`
	OperatingCashFlowGrowth                 float64 `json:"operatingCashFlowGrowth"`
	ReceivablesGrowth                       float64 `json:"receivablesGrowth"`
	InventoryGrowth                         float64 `json:"inventoryGrowth"`
	AssetGrowth                             float64 `json:"assetGrowth"`
	BookValueperShareGrowth                 float64 `json:"bookValueperShareGrowth"`
	DebtGrowth                              float64 `json:"debtGrowth"`
	RdexpenseGrowth                         float64 `json:"rdexpenseGrowth"`
	SgaexpensesGrowth                       float64 `json:"sgaexpensesGrowth"`
	FreeCashFlowGrowth                      float64 `json:"freeCashFlowGrowth"`
	TenYRevenueGrowthPerShare               float64 `json:"tenYRevenueGrowthPerShare"`
	FiveYRevenueGrowthPerShare              float64 `json:"fiveYRevenueGrowthPerShare"`
	ThreeYRevenueGrowthPerShare             float64 `json:"threeYRevenueGrowthPerShare"`
	TenYOperatingCFGrowthPerShare           float64 `json:"tenYOperatingCFGrowthPerShare"`
	FiveYOperatingCFGrowthPerShare          float64 `json:"fiveYOperatingCFGrowthPerShare"`
	ThreeYOperatingCFGrowthPerShare         float64 `json:"threeYOperatingCFGrowthPerShare"`
	TenYNetIncomeGrowthPerShare             float64 `json:"tenYNetIncomeGrowthPerShare"`
	FiveYNetIncomeGrowthPerShare            float64 `json:"fiveYNetIncomeGrowthPerShare"`
	ThreeYNetIncomeGrowthPerShare           float64 `json:"threeYNetIncomeGrowthPerShare"`
	TenYShareholdersEquityGrowthPerShare    float64 `json:"tenYShareholdersEquityGrowthPerShare"`
	FiveYShareholdersEquityGrowthPerShare   float64 `json:"fiveYShareholdersEquityGrowthPerShare"`
	ThreeYShareholdersEquityGrowthPerShare  float64 `json:"threeYShareholdersEquityGrowthPerShare"`
	TenYDividendperShareGrowthPerShare      float64 `json:"tenYDividendperShareGrowthPerShare"`
	FiveYDividendperShareGrowthPerShare     float64 `json:"fiveYDividendperShareGrowthPerShare"`
	ThreeYDividendperShareGrowthPerShare    float64 `json:"threeYDividendperShareGrowthPerShare"`
	EBITDAGrowth                            float64 `json:"ebitdaGrowth"`
	GrowthCapitalExpenditure                float64 `json:"growthCapitalExpenditure"`
	TenYBottomLineNetIncomeGrowthPerShare   float64 `json:"tenYBottomLineNetIncomeGrowthPerShare"`
	FiveYBottomLineNetIncomeGrowthPerShare  float64 `json:"fiveYBottomLineNetIncomeGrowthPerShare"`
	ThreeYBottomLineNetIncomeGrowthPerShare float64 `json:"threeYBottomLineNetIncomeGrowthPerShare"`
}

// Ratios Ratios returns valuation, profitability, and leverage ratios.
func (c *Client) Ratios(ctx context.Context, symbol string, period string, limit int) ([]Ratios, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if period != "" {
		params.Set("period", period)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []Ratios
	if err := c.get(ctx, "/ratios", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// RatiosTTM RatiosTTM returns trailing-twelve-month ratios.
func (c *Client) RatiosTTM(ctx context.Context, symbol string) (*RatiosTTM, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	var out []RatiosTTM
	if err := c.get(ctx, "/ratios-ttm", params, &out); err != nil {
		return nil, err
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("fmp: no result for RatiosTTM")
	}
	return &out[0], nil
}

// KeyMetrics KeyMetrics returns key financial metrics (market cap, EV, ROE, etc.).
func (c *Client) KeyMetrics(ctx context.Context, symbol string, period string, limit int) ([]KeyMetrics, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if period != "" {
		params.Set("period", period)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []KeyMetrics
	if err := c.get(ctx, "/key-metrics", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// KeyMetricsTTM KeyMetricsTTM returns trailing-twelve-month key metrics.
func (c *Client) KeyMetricsTTM(ctx context.Context, symbol string) (*KeyMetricsTTM, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	var out []KeyMetricsTTM
	if err := c.get(ctx, "/key-metrics-ttm", params, &out); err != nil {
		return nil, err
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("fmp: no result for KeyMetricsTTM")
	}
	return &out[0], nil
}

// FinancialGrowth FinancialGrowth returns long-term revenue, income, and FCF growth rates.
func (c *Client) FinancialGrowth(ctx context.Context, symbol string, period string, limit int) ([]FinancialGrowth, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if period != "" {
		params.Set("period", period)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []FinancialGrowth
	if err := c.get(ctx, "/financial-growth", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}
