// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"fmt"
	"net/url"
)

// SearchResult is a row returned by the FMP SearchResult endpoint.
type SearchResult struct {
	Symbol           string `json:"symbol"`
	Name             string `json:"name"`
	Currency         string `json:"currency"`
	ExchangeFullName string `json:"exchangeFullName"`
	Exchange         string `json:"exchange"`
}

// CompanyScreenerResult is a row returned by the FMP CompanyScreenerResult endpoint.
type CompanyScreenerResult struct {
	Symbol             string  `json:"symbol"`
	CompanyName        string  `json:"companyName"`
	MarketCap          int64   `json:"marketCap"`
	Sector             string  `json:"sector"`
	Industry           string  `json:"industry"`
	Beta               float64 `json:"beta"`
	Price              float64 `json:"price"`
	LastAnnualDividend float64 `json:"lastAnnualDividend"`
	Volume             int64   `json:"volume"`
	Exchange           string  `json:"exchange"`
	ExchangeShortName  string  `json:"exchangeShortName"`
	Country            string  `json:"country"`
	IsETF              bool    `json:"isEtf"`
	IsFund             bool    `json:"isFund"`
	IsActivelyTrading  bool    `json:"isActivelyTrading"`
}

// SearchSymbol search-symbol returns symbols matching a query.
func (c *Client) SearchSymbol(ctx context.Context, query string) ([]SearchResult, error) {
	params := url.Values{}
	if query != "" {
		params.Set("query", query)
	}
	var out []SearchResult
	if err := c.get(ctx, "/search-symbol", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// SearchName searches for securities whose company name matches the query.
func (c *Client) SearchName(ctx context.Context, query string) ([]SearchResult, error) {
	params := url.Values{}
	if query != "" {
		params.Set("query", query)
	}
	var out []SearchResult
	if err := c.get(ctx, "/search-name", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Screener CompanyScreener filters stocks by fundamental criteria.
func (c *Client) Screener(ctx context.Context, marketCapMoreThan int64, marketCapLessThan int64, sector string, industry string, exchange string, country string, limit int) ([]CompanyScreenerResult, error) {
	params := url.Values{}
	if marketCapMoreThan > 0 {
		params.Set("marketCapMoreThan", fmt.Sprintf("%d", marketCapMoreThan))
	}
	if marketCapLessThan > 0 {
		params.Set("marketCapLessThan", fmt.Sprintf("%d", marketCapLessThan))
	}
	if sector != "" {
		params.Set("sector", sector)
	}
	if industry != "" {
		params.Set("industry", industry)
	}
	if exchange != "" {
		params.Set("exchange", exchange)
	}
	if country != "" {
		params.Set("country", country)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []CompanyScreenerResult
	if err := c.get(ctx, "/company-screener", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}
