// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"fmt"
	"net/url"
)

// IncomeStatement is a row returned by the FMP IncomeStatement endpoint.
type IncomeStatement struct {
	Date                                    string  `json:"date"`
	Symbol                                  string  `json:"symbol"`
	ReportedCurrency                        string  `json:"reportedCurrency"`
	CIK                                     string  `json:"cik"`
	FilingDate                              string  `json:"filingDate"`
	AcceptedDate                            string  `json:"acceptedDate"`
	FiscalYear                              string  `json:"fiscalYear"`
	Period                                  string  `json:"period"`
	Revenue                                 float64 `json:"revenue"`
	CostOfRevenue                           float64 `json:"costOfRevenue"`
	GrossProfit                             float64 `json:"grossProfit"`
	ResearchAndDevelopmentExpenses          float64 `json:"researchAndDevelopmentExpenses"`
	GeneralAndAdministrativeExpenses        float64 `json:"generalAndAdministrativeExpenses"`
	SellingAndMarketingExpenses             float64 `json:"sellingAndMarketingExpenses"`
	SellingGeneralAndAdministrativeExpenses float64 `json:"sellingGeneralAndAdministrativeExpenses"`
	OtherExpenses                           float64 `json:"otherExpenses"`
	OperatingExpenses                       float64 `json:"operatingExpenses"`
	CostAndExpenses                         float64 `json:"costAndExpenses"`
	NetInterestIncome                       float64 `json:"netInterestIncome"`
	InterestIncome                          float64 `json:"interestIncome"`
	InterestExpense                         float64 `json:"interestExpense"`
	DepreciationAndAmortization             float64 `json:"depreciationAndAmortization"`
	EBITDA                                  float64 `json:"ebitda"`
	EBIT                                    float64 `json:"ebit"`
	NonOperatingIncomeExcludingInterest     float64 `json:"nonOperatingIncomeExcludingInterest"`
	OperatingIncome                         float64 `json:"operatingIncome"`
	TotalOtherIncomeExpensesNet             float64 `json:"totalOtherIncomeExpensesNet"`
	IncomeBeforeTax                         float64 `json:"incomeBeforeTax"`
	IncomeTaxExpense                        float64 `json:"incomeTaxExpense"`
	NetIncomeFromContinuingOperations       float64 `json:"netIncomeFromContinuingOperations"`
	NetIncomeFromDiscontinuedOperations     float64 `json:"netIncomeFromDiscontinuedOperations"`
	OtherAdjustmentsToNetIncome             float64 `json:"otherAdjustmentsToNetIncome"`
	NetIncome                               float64 `json:"netIncome"`
	NetIncomeDeductions                     float64 `json:"netIncomeDeductions"`
	BottomLineNetIncome                     float64 `json:"bottomLineNetIncome"`
	EPS                                     float64 `json:"eps"`
	EPSDiluted                              float64 `json:"epsDiluted"`
	WeightedAverageShsOut                   float64 `json:"weightedAverageShsOut"`
	WeightedAverageShsOutDil                float64 `json:"weightedAverageShsOutDil"`
}

// BalanceSheet is a row returned by the FMP BalanceSheet endpoint.
type BalanceSheet struct {
	Date                                    string  `json:"date"`
	Symbol                                  string  `json:"symbol"`
	ReportedCurrency                        string  `json:"reportedCurrency"`
	CIK                                     string  `json:"cik"`
	FilingDate                              string  `json:"filingDate"`
	AcceptedDate                            string  `json:"acceptedDate"`
	FiscalYear                              string  `json:"fiscalYear"`
	Period                                  string  `json:"period"`
	CashAndCashEquivalents                  float64 `json:"cashAndCashEquivalents"`
	ShortTermInvestments                    float64 `json:"shortTermInvestments"`
	CashAndShortTermInvestments             float64 `json:"cashAndShortTermInvestments"`
	NetReceivables                          float64 `json:"netReceivables"`
	AccountsReceivables                     float64 `json:"accountsReceivables"`
	OtherReceivables                        float64 `json:"otherReceivables"`
	Inventory                               float64 `json:"inventory"`
	Prepaids                                float64 `json:"prepaids"`
	OtherCurrentAssets                      float64 `json:"otherCurrentAssets"`
	TotalCurrentAssets                      float64 `json:"totalCurrentAssets"`
	PropertyPlantEquipmentNet               float64 `json:"propertyPlantEquipmentNet"`
	Goodwill                                float64 `json:"goodwill"`
	IntangibleAssets                        float64 `json:"intangibleAssets"`
	GoodwillAndIntangibleAssets             float64 `json:"goodwillAndIntangibleAssets"`
	LongTermInvestments                     float64 `json:"longTermInvestments"`
	TaxAssets                               float64 `json:"taxAssets"`
	OtherNonCurrentAssets                   float64 `json:"otherNonCurrentAssets"`
	TotalNonCurrentAssets                   float64 `json:"totalNonCurrentAssets"`
	OtherAssets                             float64 `json:"otherAssets"`
	TotalAssets                             float64 `json:"totalAssets"`
	TotalPayables                           float64 `json:"totalPayables"`
	AccountPayables                         float64 `json:"accountPayables"`
	OtherPayables                           float64 `json:"otherPayables"`
	AccruedExpenses                         float64 `json:"accruedExpenses"`
	ShortTermDebt                           float64 `json:"shortTermDebt"`
	CapitalLeaseObligationsCurrent          float64 `json:"capitalLeaseObligationsCurrent"`
	TaxPayables                             float64 `json:"taxPayables"`
	DeferredRevenue                         float64 `json:"deferredRevenue"`
	OtherCurrentLiabilities                 float64 `json:"otherCurrentLiabilities"`
	TotalCurrentLiabilities                 float64 `json:"totalCurrentLiabilities"`
	LongTermDebt                            float64 `json:"longTermDebt"`
	CapitalLeaseObligationsNonCurrent       float64 `json:"capitalLeaseObligationsNonCurrent"`
	DeferredRevenueNonCurrent               float64 `json:"deferredRevenueNonCurrent"`
	DeferredTaxLiabilitiesNonCurrent        float64 `json:"deferredTaxLiabilitiesNonCurrent"`
	OtherNonCurrentLiabilities              float64 `json:"otherNonCurrentLiabilities"`
	TotalNonCurrentLiabilities              float64 `json:"totalNonCurrentLiabilities"`
	OtherLiabilities                        float64 `json:"otherLiabilities"`
	CapitalLeaseObligations                 float64 `json:"capitalLeaseObligations"`
	TotalLiabilities                        float64 `json:"totalLiabilities"`
	TreasuryStock                           float64 `json:"treasuryStock"`
	PreferredStock                          float64 `json:"preferredStock"`
	CommonStock                             float64 `json:"commonStock"`
	RetainedEarnings                        float64 `json:"retainedEarnings"`
	AdditionalPaidInCapital                 float64 `json:"additionalPaidInCapital"`
	AccumulatedOtherComprehensiveIncomeLoss float64 `json:"accumulatedOtherComprehensiveIncomeLoss"`
	OtherTotalStockholdersEquity            float64 `json:"otherTotalStockholdersEquity"`
	TotalStockholdersEquity                 float64 `json:"totalStockholdersEquity"`
	TotalEquity                             float64 `json:"totalEquity"`
	MinorityInterest                        float64 `json:"minorityInterest"`
	TotalLiabilitiesAndTotalEquity          float64 `json:"totalLiabilitiesAndTotalEquity"`
	TotalInvestments                        float64 `json:"totalInvestments"`
	TotalDebt                               float64 `json:"totalDebt"`
	NetDebt                                 float64 `json:"netDebt"`
}

// CashFlowStatement is a row returned by the FMP CashFlowStatement endpoint.
type CashFlowStatement struct {
	Date                                   string  `json:"date"`
	Symbol                                 string  `json:"symbol"`
	ReportedCurrency                       string  `json:"reportedCurrency"`
	CIK                                    string  `json:"cik"`
	FilingDate                             string  `json:"filingDate"`
	AcceptedDate                           string  `json:"acceptedDate"`
	FiscalYear                             string  `json:"fiscalYear"`
	Period                                 string  `json:"period"`
	NetIncome                              float64 `json:"netIncome"`
	DepreciationAndAmortization            float64 `json:"depreciationAndAmortization"`
	DeferredIncomeTax                      float64 `json:"deferredIncomeTax"`
	StockBasedCompensation                 float64 `json:"stockBasedCompensation"`
	ChangeInWorkingCapital                 float64 `json:"changeInWorkingCapital"`
	AccountsReceivables                    float64 `json:"accountsReceivables"`
	Inventory                              float64 `json:"inventory"`
	AccountsPayables                       float64 `json:"accountsPayables"`
	OtherWorkingCapital                    float64 `json:"otherWorkingCapital"`
	OtherNonCashItems                      float64 `json:"otherNonCashItems"`
	NetCashProvidedByOperatingActivities   float64 `json:"netCashProvidedByOperatingActivities"`
	InvestmentsInPropertyPlantAndEquipment float64 `json:"investmentsInPropertyPlantAndEquipment"`
	AcquisitionsNet                        float64 `json:"acquisitionsNet"`
	PurchasesOfInvestments                 float64 `json:"purchasesOfInvestments"`
	SalesMaturitiesOfInvestments           float64 `json:"salesMaturitiesOfInvestments"`
	OtherInvestingActivities               float64 `json:"otherInvestingActivities"`
	NetCashProvidedByInvestingActivities   float64 `json:"netCashProvidedByInvestingActivities"`
	NetDebtIssuance                        float64 `json:"netDebtIssuance"`
	LongTermNetDebtIssuance                float64 `json:"longTermNetDebtIssuance"`
	ShortTermNetDebtIssuance               float64 `json:"shortTermNetDebtIssuance"`
	NetStockIssuance                       float64 `json:"netStockIssuance"`
	NetCommonStockIssuance                 float64 `json:"netCommonStockIssuance"`
	CommonStockIssuance                    float64 `json:"commonStockIssuance"`
	CommonStockRepurchased                 float64 `json:"commonStockRepurchased"`
	NetPreferredStockIssuance              float64 `json:"netPreferredStockIssuance"`
	NetDividendsPaid                       float64 `json:"netDividendsPaid"`
	CommonDividendsPaid                    float64 `json:"commonDividendsPaid"`
	PreferredDividendsPaid                 float64 `json:"preferredDividendsPaid"`
	OtherFinancingActivities               float64 `json:"otherFinancingActivities"`
	NetCashProvidedByFinancingActivities   float64 `json:"netCashProvidedByFinancingActivities"`
	EffectOfForexChangesOnCash             float64 `json:"effectOfForexChangesOnCash"`
	NetChangeInCash                        float64 `json:"netChangeInCash"`
	CashAtEndOfPeriod                      float64 `json:"cashAtEndOfPeriod"`
	CashAtBeginningOfPeriod                float64 `json:"cashAtBeginningOfPeriod"`
	OperatingCashFlow                      float64 `json:"operatingCashFlow"`
	CapitalExpenditure                     float64 `json:"capitalExpenditure"`
	FreeCashFlow                           float64 `json:"freeCashFlow"`
	IncomeTaxesPaid                        float64 `json:"incomeTaxesPaid"`
	InterestPaid                           float64 `json:"interestPaid"`
}

// IncomeStatements IncomeStatements returns income statements.
func (c *Client) IncomeStatements(ctx context.Context, symbol string, period string, limit int) ([]IncomeStatement, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if period != "" {
		params.Set("period", period)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []IncomeStatement
	if err := c.get(ctx, "/income-statement", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceSheets BalanceSheets returns balance sheet statements.
func (c *Client) BalanceSheets(ctx context.Context, symbol string, period string, limit int) ([]BalanceSheet, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if period != "" {
		params.Set("period", period)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []BalanceSheet
	if err := c.get(ctx, "/balance-sheet-statement", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// CashFlowStatements CashFlowStatements returns cash flow statements.
func (c *Client) CashFlowStatements(ctx context.Context, symbol string, period string, limit int) ([]CashFlowStatement, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if period != "" {
		params.Set("period", period)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []CashFlowStatement
	if err := c.get(ctx, "/cash-flow-statement", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}
