// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"fmt"
	"net/url"
)


// IncomeStatement is a row returned by the FMP IncomeStatement endpoint.
type IncomeStatement struct {
	Date string `json:"date"`
	Symbol string `json:"symbol"`
	ReportedCurrency string `json:"reportedCurrency"`
	CIK string `json:"cik"`
	FilingDate string `json:"filingDate"`
	AcceptedDate string `json:"acceptedDate"`
	FiscalYear string `json:"fiscalYear"`
	Period string `json:"period"`
	Revenue int64 `json:"revenue"`
	CostOfRevenue int64 `json:"costOfRevenue"`
	GrossProfit int64 `json:"grossProfit"`
	ResearchAndDevelopmentExpenses int64 `json:"researchAndDevelopmentExpenses"`
	GeneralAndAdministrativeExpenses int64 `json:"generalAndAdministrativeExpenses"`
	SellingAndMarketingExpenses int64 `json:"sellingAndMarketingExpenses"`
	SellingGeneralAndAdministrativeExpenses int64 `json:"sellingGeneralAndAdministrativeExpenses"`
	OtherExpenses int64 `json:"otherExpenses"`
	OperatingExpenses int64 `json:"operatingExpenses"`
	CostAndExpenses int64 `json:"costAndExpenses"`
	NetInterestIncome int64 `json:"netInterestIncome"`
	InterestIncome int64 `json:"interestIncome"`
	InterestExpense int64 `json:"interestExpense"`
	DepreciationAndAmortization int64 `json:"depreciationAndAmortization"`
	EBITDA int64 `json:"ebitda"`
	EBIT int64 `json:"ebit"`
	NonOperatingIncomeExcludingInterest int64 `json:"nonOperatingIncomeExcludingInterest"`
	OperatingIncome int64 `json:"operatingIncome"`
	TotalOtherIncomeExpensesNet int64 `json:"totalOtherIncomeExpensesNet"`
	IncomeBeforeTax int64 `json:"incomeBeforeTax"`
	IncomeTaxExpense int64 `json:"incomeTaxExpense"`
	NetIncomeFromContinuingOperations int64 `json:"netIncomeFromContinuingOperations"`
	NetIncomeFromDiscontinuedOperations int64 `json:"netIncomeFromDiscontinuedOperations"`
	OtherAdjustmentsToNetIncome int64 `json:"otherAdjustmentsToNetIncome"`
	NetIncome int64 `json:"netIncome"`
	NetIncomeDeductions int64 `json:"netIncomeDeductions"`
	BottomLineNetIncome int64 `json:"bottomLineNetIncome"`
	EPS float64 `json:"eps"`
	EPSDiluted float64 `json:"epsDiluted"`
	WeightedAverageShsOut int64 `json:"weightedAverageShsOut"`
	WeightedAverageShsOutDil int64 `json:"weightedAverageShsOutDil"`
}

// BalanceSheet is a row returned by the FMP BalanceSheet endpoint.
type BalanceSheet struct {
	Date string `json:"date"`
	Symbol string `json:"symbol"`
	ReportedCurrency string `json:"reportedCurrency"`
	CIK string `json:"cik"`
	FilingDate string `json:"filingDate"`
	AcceptedDate string `json:"acceptedDate"`
	FiscalYear string `json:"fiscalYear"`
	Period string `json:"period"`
	CashAndCashEquivalents int64 `json:"cashAndCashEquivalents"`
	ShortTermInvestments int64 `json:"shortTermInvestments"`
	CashAndShortTermInvestments int64 `json:"cashAndShortTermInvestments"`
	NetReceivables int64 `json:"netReceivables"`
	AccountsReceivables int64 `json:"accountsReceivables"`
	OtherReceivables int64 `json:"otherReceivables"`
	Inventory int64 `json:"inventory"`
	Prepaids int64 `json:"prepaids"`
	OtherCurrentAssets int64 `json:"otherCurrentAssets"`
	TotalCurrentAssets int64 `json:"totalCurrentAssets"`
	PropertyPlantEquipmentNet int64 `json:"propertyPlantEquipmentNet"`
	Goodwill int64 `json:"goodwill"`
	IntangibleAssets int64 `json:"intangibleAssets"`
	GoodwillAndIntangibleAssets int64 `json:"goodwillAndIntangibleAssets"`
	LongTermInvestments int64 `json:"longTermInvestments"`
	TaxAssets int64 `json:"taxAssets"`
	OtherNonCurrentAssets int64 `json:"otherNonCurrentAssets"`
	TotalNonCurrentAssets int64 `json:"totalNonCurrentAssets"`
	OtherAssets int64 `json:"otherAssets"`
	TotalAssets int64 `json:"totalAssets"`
	TotalPayables int64 `json:"totalPayables"`
	AccountPayables int64 `json:"accountPayables"`
	OtherPayables int64 `json:"otherPayables"`
	AccruedExpenses int64 `json:"accruedExpenses"`
	ShortTermDebt int64 `json:"shortTermDebt"`
	CapitalLeaseObligationsCurrent int64 `json:"capitalLeaseObligationsCurrent"`
	TaxPayables int64 `json:"taxPayables"`
	DeferredRevenue int64 `json:"deferredRevenue"`
	OtherCurrentLiabilities int64 `json:"otherCurrentLiabilities"`
	TotalCurrentLiabilities int64 `json:"totalCurrentLiabilities"`
	LongTermDebt int64 `json:"longTermDebt"`
	CapitalLeaseObligationsNonCurrent int64 `json:"capitalLeaseObligationsNonCurrent"`
	DeferredRevenueNonCurrent int64 `json:"deferredRevenueNonCurrent"`
	DeferredTaxLiabilitiesNonCurrent int64 `json:"deferredTaxLiabilitiesNonCurrent"`
	OtherNonCurrentLiabilities int64 `json:"otherNonCurrentLiabilities"`
	TotalNonCurrentLiabilities int64 `json:"totalNonCurrentLiabilities"`
	OtherLiabilities int64 `json:"otherLiabilities"`
	CapitalLeaseObligations int64 `json:"capitalLeaseObligations"`
	TotalLiabilities int64 `json:"totalLiabilities"`
	TreasuryStock int64 `json:"treasuryStock"`
	PreferredStock int64 `json:"preferredStock"`
	CommonStock int64 `json:"commonStock"`
	RetainedEarnings int64 `json:"retainedEarnings"`
	AdditionalPaidInCapital int64 `json:"additionalPaidInCapital"`
	AccumulatedOtherComprehensiveIncomeLoss int64 `json:"accumulatedOtherComprehensiveIncomeLoss"`
	OtherTotalStockholdersEquity int64 `json:"otherTotalStockholdersEquity"`
	TotalStockholdersEquity int64 `json:"totalStockholdersEquity"`
	TotalEquity int64 `json:"totalEquity"`
	MinorityInterest int64 `json:"minorityInterest"`
	TotalLiabilitiesAndTotalEquity int64 `json:"totalLiabilitiesAndTotalEquity"`
	TotalInvestments int64 `json:"totalInvestments"`
	TotalDebt int64 `json:"totalDebt"`
	NetDebt int64 `json:"netDebt"`
}

// CashFlowStatement is a row returned by the FMP CashFlowStatement endpoint.
type CashFlowStatement struct {
	Date string `json:"date"`
	Symbol string `json:"symbol"`
	ReportedCurrency string `json:"reportedCurrency"`
	CIK string `json:"cik"`
	FilingDate string `json:"filingDate"`
	AcceptedDate string `json:"acceptedDate"`
	FiscalYear string `json:"fiscalYear"`
	Period string `json:"period"`
	NetIncome int64 `json:"netIncome"`
	DepreciationAndAmortization int64 `json:"depreciationAndAmortization"`
	DeferredIncomeTax int64 `json:"deferredIncomeTax"`
	StockBasedCompensation int64 `json:"stockBasedCompensation"`
	ChangeInWorkingCapital int64 `json:"changeInWorkingCapital"`
	AccountsReceivables int64 `json:"accountsReceivables"`
	Inventory int64 `json:"inventory"`
	AccountsPayables int64 `json:"accountsPayables"`
	OtherWorkingCapital int64 `json:"otherWorkingCapital"`
	OtherNonCashItems int64 `json:"otherNonCashItems"`
	NetCashProvidedByOperatingActivities int64 `json:"netCashProvidedByOperatingActivities"`
	InvestmentsInPropertyPlantAndEquipment int64 `json:"investmentsInPropertyPlantAndEquipment"`
	AcquisitionsNet int64 `json:"acquisitionsNet"`
	PurchasesOfInvestments int64 `json:"purchasesOfInvestments"`
	SalesMaturitiesOfInvestments int64 `json:"salesMaturitiesOfInvestments"`
	OtherInvestingActivities int64 `json:"otherInvestingActivities"`
	NetCashProvidedByInvestingActivities int64 `json:"netCashProvidedByInvestingActivities"`
	NetDebtIssuance int64 `json:"netDebtIssuance"`
	LongTermNetDebtIssuance int64 `json:"longTermNetDebtIssuance"`
	ShortTermNetDebtIssuance int64 `json:"shortTermNetDebtIssuance"`
	NetStockIssuance int64 `json:"netStockIssuance"`
	NetCommonStockIssuance int64 `json:"netCommonStockIssuance"`
	CommonStockIssuance int64 `json:"commonStockIssuance"`
	CommonStockRepurchased int64 `json:"commonStockRepurchased"`
	NetPreferredStockIssuance int64 `json:"netPreferredStockIssuance"`
	NetDividendsPaid int64 `json:"netDividendsPaid"`
	CommonDividendsPaid int64 `json:"commonDividendsPaid"`
	PreferredDividendsPaid int64 `json:"preferredDividendsPaid"`
	OtherFinancingActivities int64 `json:"otherFinancingActivities"`
	NetCashProvidedByFinancingActivities int64 `json:"netCashProvidedByFinancingActivities"`
	EffectOfForexChangesOnCash int64 `json:"effectOfForexChangesOnCash"`
	NetChangeInCash int64 `json:"netChangeInCash"`
	CashAtEndOfPeriod int64 `json:"cashAtEndOfPeriod"`
	CashAtBeginningOfPeriod int64 `json:"cashAtBeginningOfPeriod"`
	OperatingCashFlow int64 `json:"operatingCashFlow"`
	CapitalExpenditure int64 `json:"capitalExpenditure"`
	FreeCashFlow int64 `json:"freeCashFlow"`
	IncomeTaxesPaid int64 `json:"incomeTaxesPaid"`
	InterestPaid int64 `json:"interestPaid"`
}

// IncomeStatements IncomeStatements returns income statements.
func (c *Client) IncomeStatements(ctx context.Context, symbol string, period string, limit int) ([]IncomeStatement, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if period != "" {
		params.Set("period", period)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []IncomeStatement
	if err := c.get(ctx, "/income-statement", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceSheets BalanceSheets returns balance sheet statements.
func (c *Client) BalanceSheets(ctx context.Context, symbol string, period string, limit int) ([]BalanceSheet, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if period != "" {
		params.Set("period", period)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []BalanceSheet
	if err := c.get(ctx, "/balance-sheet-statement", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// CashFlowStatements CashFlowStatements returns cash flow statements.
func (c *Client) CashFlowStatements(ctx context.Context, symbol string, period string, limit int) ([]CashFlowStatement, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	if period != "" {
		params.Set("period", period)
	}
	if limit > 0 {
		params.Set("limit", fmt.Sprintf("%d", limit))
	}
	var out []CashFlowStatement
	if err := c.get(ctx, "/cash-flow-statement", params, &out); err != nil {
		return nil, err
	}
	return out, nil
}
