// Code generated by generate.py — DO NOT EDIT.
// Re-run: python3 generate.py
package fmp

import (
	"context"
	"fmt"
	"net/url"
)


// DCF is a row returned by the FMP DCF endpoint.
type DCF struct {
	Symbol string `json:"symbol"`
	Date string `json:"date"`
	DCF float64 `json:"dcf"`
	Stockprice float64 `json:"Stock Price"`
}

// DCF DCF returns the current DCF valuation estimate.
func (c *Client) DCF(ctx context.Context, symbol string) (*DCF, error) {
	params := url.Values{}
	if symbol != "" {
		params.Set("symbol", symbol)
	}
	var out []DCF
	if err := c.get(ctx, "/discounted-cash-flow", params, &out); err != nil {
		return nil, err
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("fmp: no result for DCF")
	}
	return &out[0], nil
}
